global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'orderfront'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['orderfront:4000']

  - job_name: 'matchingengine'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'matchingengine:4001' ]

  - job_name: 'orderbook-microservices-apigateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['orderbook-microservices-apigateway:4999']